/**
 * Translate the in-app SeherConfig (saved via `settings.app-save` from the
 * SwiftUI Settings tab) into seher-ts 0.1.13+ `config.yaml` format and write
 * it to a fixed path so the SeherSDK in `router.ts` picks it up.
 *
 * Output path defaults to
 *   `$XDG_CONFIG_HOME/smartcrab/seher-config.yaml`
 * and is overridable through `SMARTCRAB_SEHER_CONFIG`.
 */

import { mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import YAML from "yaml";

import {
  translate,
  type SmartCrabConfig,
  type PriorityRule,
  type ProviderConfig,
  type DefaultsConfig,
  type SeherConfig,
} from "@smartcrab/seher-config-schema";
import type { ProviderKind } from "@smartcrab/seher-config-schema";

import { configDir } from "../paths.ts";

// ── In-app configuration types (RPC DTOs from SwiftUI) ─────────────────────

interface InAppProvider {
  id: string;
  kind: ProviderKind;
  model: string;
  envOverrides?: Record<string, string>;
}

interface InAppPriorityRule {
  providerId: string;
  weight: number;
  weekdayFilter?: number[];
  hourStart?: number;
  hourEnd?: number;
  condition?: string;
}

interface InAppDefaults {
  fallbackProviderId: string;
  rateLimitBackoffSeconds: number;
}

export interface InAppSeherConfig {
  providers: InAppProvider[];
  priorities: InAppPriorityRule[];
  defaults: InAppDefaults;
}

// ── Path helpers ───────────────────────────────────────────────────────────

export function defaultSeherConfigPath(): string {
  return process.env.SMARTCRAB_SEHER_CONFIG || join(configDir(), "seher-config.yaml");
}

// ── Adapter: InAppSeherConfig → SmartCrabConfig ────────────────────────────

function toSmartCrabConfig(cfg: InAppSeherConfig): SmartCrabConfig {
  const providers: ProviderConfig[] = cfg.providers.map((p) => ({
    id: p.id,
    kind: p.kind,
    model: p.model || undefined,
    envOverrides: p.envOverrides,
  }));

  const priority: PriorityRule[] = cfg.priorities.map((r) => ({
    providerId: r.providerId,
    weight: r.weight,
  }));

  const defaults: DefaultsConfig = {
    fallbackProviderId: cfg.defaults.fallbackProviderId,
    rateLimitBackoffSec: cfg.defaults.rateLimitBackoffSeconds,
  };

  return { providers, priority, defaults };
}

// ── Translation (delegates to the shared pure translator) ──────────────────

/**
 * Translate in-app config to the seher-ts `config.yaml` shape.
 * Delegates to `@smartcrab/seher-config-schema` for the canonical translation.
 */
export function translateToSeherConfig(cfg: InAppSeherConfig): SeherConfig {
  return translate(toSmartCrabConfig(cfg));
}

// ── File I/O ────────────────────────────────────────────────────────────────

const BANNER = `# Generated by SmartCrab from the in-app Settings tab. Do not edit by hand —
# changes will be overwritten on the next \`settings.app-save\`.
`;

/**
 * Write the translated seher-ts config YAML to disk.
 * Idempotent: skips the write when the file already matches (tmp+rename for
 * atomicity so a concurrently running seher-ts never sees a partial file).
 */
export function writeSeherConfig(
  cfg: InAppSeherConfig,
  path: string = defaultSeherConfigPath(),
): void {
  const config = translateToSeherConfig(cfg);

  const lines = BANNER + YAML.stringify(config);

  mkdirSync(dirname(path), { recursive: true });

  // Idempotency: skip write if content is identical
  try {
    if (readFileSync(path, "utf8") === lines) return;
  } catch (err) {
    // Only ignore missing-file errors; re-throw permission/disk errors
    if (!(err instanceof Error) || (err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  const tmp = `${path}.tmp`;
  writeFileSync(tmp, lines, "utf8");
  renameSync(tmp, path);
}
