services:
  jaeger:
    image: jaegertracing/jaeger:latest@sha256:bf7f805da4c2bc8d58a6c81ee650fdb6b8e4287698f95fbe231c09c865bc397f
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
